[general]
email = "your_email@example.com"

[server]
headless = true
port = 8501
enableCORS = false
maxUploadSize = 10000 
maxMessageSize = 18000  # For WebSocket messages
fileWatcherTimeout = 30000

[theme]
primaryColor = "#F39C12"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F7F7F7"
textColor = "#000000"
font = "sans serif"